#!/bin/sh
# Generates node.json from env vars and starts avalanchego tracking the ZCore L1 (on Fuji).
# PUBLIC_IP is auto-detected (via https://api.ipify.org) — set it only to override. The node's
# identity keys (NodeID/BLS) are generated by avalanchego itself in $DATA/staking on first boot —
# persist the volume!
#
# The node joins the Avalanche Fuji testnet (bootstraps from Fuji's official seeders — no
# custom genesis needed) with partial sync: it only syncs the P-Chain plus the ZCore L1,
# keeping disk and bandwidth usage low.
set -e

# Public IP: use PUBLIC_IP if provided, otherwise auto-detect it (the node advertises this to
# peers, so it must be the server's real public IP).
if [ -z "${PUBLIC_IP:-}" ]; then
  echo "PUBLIC_IP not set — auto-detecting the public IP…"
  PUBLIC_IP="$(curl -fsS --max-time 10 https://api.ipify.org 2>/dev/null || true)"
  [ -z "$PUBLIC_IP" ] && PUBLIC_IP="$(curl -fsS --max-time 10 https://ifconfig.me 2>/dev/null || true)"
fi
[ -n "${PUBLIC_IP:-}" ] || { echo "ERROR: could not auto-detect the public IP. Set it explicitly, e.g. -e PUBLIC_IP=<your.public.ip>"; exit 1; }

DATA=/root/.avalanchego
mkdir -p "$DATA/configs" "$DATA/logs"

# ZCore L1 subnet on Fuji — overridable via env, defaults to the official one.
SUBNET="${SUBNET_ID:-2pTqqpENtHTi118Dh4PSbLkjA6ySpBBeRTK9emcrfksDFytAdg}"

cat > "$DATA/configs/node.json" <<JSON
{
  "network-id": "fuji",
  "data-dir": "$DATA",
  "public-ip": "${PUBLIC_IP}",
  "http-host": "0.0.0.0",
  "http-port": 9650,
  "http-allowed-hosts": ["*"],
  "staking-port": 9651,
  "track-subnets": "${SUBNET}",
  "partial-sync-primary-network": true,
  "log-level": "info",
  "log-display-level": "info"
}
JSON

echo "==================== ZCore validator node ===================="
echo "  public-ip    : ${PUBLIC_IP}"
echo "  network      : fuji (partial sync — P-Chain + ZCore L1 only)"
echo "  track-subnet : ${SUBNET}"
echo "  identity     : ${DATA}/staking (persist the volume to keep your NodeID)"
echo "=============================================================="
exec avalanchego --config-file="$DATA/configs/node.json"
